/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLACKJACK_H_RPCGEN
#define _BLACKJACK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Hand {
	int player_cards[50];
	int player_count;
	int dealer_cards[50];
	int dealer_count;
};
typedef struct Hand Hand;

struct Result {
	int player;
	int dealer;
};
typedef struct Result Result;

#define BLACKJACK_PROG 123456
#define BLACKJACK_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define START_GAME 1
extern  struct Hand * start_game_1(void *, CLIENT *);
extern  struct Hand * start_game_1_svc(void *, struct svc_req *);
#define HIT 2
extern  struct Hand * hit_1(void *, CLIENT *);
extern  struct Hand * hit_1_svc(void *, struct svc_req *);
#define STAND 3
extern  struct Hand * stand_1(void *, CLIENT *);
extern  struct Hand * stand_1_svc(void *, struct svc_req *);
#define GET_RESULT 4
extern  struct Result * get_result_1(void *, CLIENT *);
extern  struct Result * get_result_1_svc(void *, struct svc_req *);
extern int blackjack_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define START_GAME 1
extern  struct Hand * start_game_1();
extern  struct Hand * start_game_1_svc();
#define HIT 2
extern  struct Hand * hit_1();
extern  struct Hand * hit_1_svc();
#define STAND 3
extern  struct Hand * stand_1();
extern  struct Hand * stand_1_svc();
#define GET_RESULT 4
extern  struct Result * get_result_1();
extern  struct Result * get_result_1_svc();
extern int blackjack_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Hand (XDR *, Hand*);
extern  bool_t xdr_Result (XDR *, Result*);

#else /* K&R C */
extern bool_t xdr_Hand ();
extern bool_t xdr_Result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLACKJACK_H_RPCGEN */
