/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "BlackJack.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct Hand *
start_game_1(void *argp, CLIENT *clnt)
{
	static struct Hand clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, START_GAME,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Hand, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Hand *
hit_1(void *argp, CLIENT *clnt)
{
	static struct Hand clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, HIT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Hand, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Hand *
stand_1(void *argp, CLIENT *clnt)
{
	static struct Hand clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STAND,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Hand, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Result *
get_result_1(void *argp, CLIENT *clnt)
{
	static struct Result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_RESULT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_Result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
