/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "BlackJack.h"

struct Hand *
start_game_1_svc(void *argp, struct svc_req *rqstp)
{
	static struct Hand  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct Hand *
hit_1_svc(void *argp, struct svc_req *rqstp)
{
	static struct Hand  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct Hand *
stand_1_svc(void *argp, struct svc_req *rqstp)
{
	static struct Hand  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct Result *
get_result_1_svc(void *argp, struct svc_req *rqstp)
{
	static struct Result  result;

	/*
	 * insert server code here
	 */

	return &result;
}
